alias cls=clear
alias ut=uptime
alias dl="clear ; echo '-------------- Directory ------------------' ; ls -ls | more"
alias da="clear ; echo '-------------- Directory ------------------' ; ls -lsa | more"
