alias cls=clear
alias ut=uptime
alias dl="clear ; echo '-------------- Directory ------------------' ; ls -ls | more"
alias da="clear ; echo '-------------- Directory ------------------' ; ls -lsa | more"
#
# For OSX
#alias dl="clear ; echo '-------------- Directory ------------------' ; CLICOLOR_FORCE=1 ls -ls | less -ceFRX"
#alias da="clear ; echo '-------------- Directory ------------------' ; CLICOLOR_FORCE=1 ls -lsa | less -ceFRX"
#
